### PR TITLE
Fixed compilation with GHC 8.4.1-alpha1

### PR DESCRIPTION
**Pull request by asr**
GHC 8.4.1-alpha1 was [announced](https://mail.haskell.org/pipermail/ghc-devs/2017-December/015235.html). While testing [Agda](https://github.com/agda/agda) with this version of GHC, I got the following error (modulo some dependencies):

```
$ cabal install
...
[ 2 of 10] Compiling System.Process.Common ( src/System/Process/Common.hs, dist/build/System/Process/Common.o )

src/System/Process/Common.hs:92:10: error:
    • No instance for (Semigroup ExitCode)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid ExitCode’
   |
92 | instance Monoid ExitCode where
   |          ^^^^^^^^^^^^^^^
Failed to install process-extras-0.7.2
```

This PR fix the above error.

Blocking https://github.com/agda/agda/issues/2878.

### CODE REVIEW

**Comment by ddssff** [comment]
Uploaded to hackage as 0.7.3

**Comment by asr** [comment]
Great! Thanks!

**Comment by asr** [comment]
Thanks for the release, please note you didn't update the changelog.

**Comment by ddssff** [comment]
Hmm, forgot I had a changelog!

**Pull request merged**
